# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 14:26
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, help_text='Who wrote/sent/created this document', max_length=128, null=True)),
                ('date', models.DateField(blank=True, help_text='The date printed on the document', null=True)),
                ('time', models.TimeField(blank=True, help_text='The time printed on the document', null=True)),
                ('source', models.CharField(default='Manually imported', help_text='How this document made its way into the system', max_length=128)),
                ('imported', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='')),
                ('doxieapi_scan_json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
    ]
