# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='imported_ok',
            field=models.BooleanField(default=False),
        ),
    ]
