# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_imported_ok'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='other_pages',
            field=models.ManyToManyField(related_name='_document_other_pages_+', to='documents.Document'),
        ),
        migrations.AddField(
            model_name='document',
            name='page_number',
            field=models.IntegerField(default=1),
        ),
    ]
