# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20160128_2040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('-imported',)},
        ),
    ]
