# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_auto_20160128_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='original_kept',
            field=models.BooleanField(default=True, help_text='Whether the original physical copy of this document has been kept'),
        ),
        migrations.AddField(
            model_name='document',
            name='original_location',
            field=models.CharField(blank=True, help_text='Where the physical copy of this document is kept', max_length=256, null=True),
        ),
    ]
