# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_auto_20160130_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='filehash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
