# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_document_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='source',
            field=models.CharField(default='Manually uploaded', help_text='How this document made its way into the system', max_length=128),
        ),
    ]
