# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_auto_20160131_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=documents.models.document_file_thumbnail_upload_path),
        ),
    ]
