# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_auto_20160212_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_thumbnail_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='file_thumbnail_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_thumbnail',
            field=models.ImageField(blank=True, height_field='file_thumbnail_height', null=True, upload_to=documents.models.document_file_thumbnail_upload_path, width_field='file_thumbnail_width'),
        ),
    ]
