# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 22:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_auto_20171105_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file_thumbnail',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file_thumbnail_height',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file_thumbnail_width',
        ),
    ]
