# Generated by Django 2.2.4 on 2019-08-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_auto_20171105_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ocr_job_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='ocr_status',
            field=models.CharField(choices=[('new', 'New'), ('pending', 'Pending'), ('complete', 'Complete'), ('failed', 'Failed')], default='new', max_length=16),
        ),
        migrations.AddField(
            model_name='document',
            name='ocr_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
