# Generated by Django 2.2.5 on 2019-09-05 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_auto_20190821_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='doxieapi_scan_json',
            new_name='source_metadata',
        ),
    ]
