# Generated by Django 3.1 on 2020-08-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_auto_20190905_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='source_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
