#!/bin/sh
APPDIR=..
VENVDIR=../../venv-documentstore

$VENVDIR/bin/pip install -r $APPDIR/requirements.txt

# $VENVDIR/bin/python $APPDIR/manage.py migrate
# $VENVDIR/bin/python $APPDIR/manage.py collectstatic --noinput
